setup.py
flake8 testing of https://github.com/Microsoft/dowhy on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./setup.py:47:20: E999 SyntaxError: invalid syntax
install_requires=['numpy', 'scikit-learn', 'matplotlib', 'scipy', 
^
1     E999 SyntaxError: invalid syntax
1
```
=> Syntax Error: missing comma between function parameters

dowhy/causal_estimator.py, dowhy/causal_estimators/__init__.py, dowhy/causal_estimators/instrumental_variable_estimator.py, dowhy/causal_estimators/linear_regression_estimator.py, dowhy/causal_estimators/propensity_score_matching_estimator.py, dowhy/causal_estimators/propensity_score_stratification_estimator.py, dowhy/causal_estimators/propensity_score_weighting_estimator.py, dowhy/causal_estimators/regression_discontinuity_estimator.py, dowhy/causal_graph.py, dowhy/causal_identifier.py, dowhy/causal_refuter.py, dowhy/causal_refuters/__init__.py, dowhy/causal_refuters/data_subset_refuter.py, dowhy/causal_refuters/placebo_treatment_refuter.py, dowhy/causal_refuters/random_common_cause.py, dowhy/data_transformer.py, dowhy/data_transformers/pca_reducer.py, dowhy/datasets.py, dowhy/do_why.py, dowhy/plotter.py, dowhy/utils/cli_helpers.py, setup.py, tests/causal_estimators/test_linear_regression_estimator.py, tests/data_transformers/test_pca_reducer.py, tests/definitions.py, tests/test_causal_estimator.py
Clean up the code a bit (mostly standard PyCharm fixes). Changes are generally for style, little functional changes:
- Remove unused imports and reorder them.
- Fix indentation.
- Remove trailing whitespaces.
- Fix whitespace around operators.
- Fix some of the line lengths.
- Fix some of the commented-out code.
This PR reduces [flake8](http://flake8.pycqa.org/en/latest/)'s total number of warnings & errors from 578 to 130.
=> Fix flake8 warnings & errors

README.rst
Add space around the assignment operator in the examples.
=> Make examples PEP8 compliant.

requirements.txt
When running `python setup.py test` on a fresh 3.6 virtualenv:
```
[...]
======================================================================
ERROR: linear_regression_estimator (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: linear_regression_estimator
Traceback (most recent call last):
File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
module = __import__(module_name)
File "/tmp/dowhy/dowhy/causal_estimators/linear_regression_estimator.py", line 2, in <module>
from sklearn import linear_model
ModuleNotFoundError: No module named 'sklearn'
----------------------------------------------------------------------
Ran 5 tests in 0.001s
FAILED (errors=5)
Test failed: …
```
=> Missing sklearn dependency

README.rst
This minor pull request fixes a few issues in the readme: Trailing whitespace and PEP8 compliance for the python example code.
I note that #17 tried to solve some of the same goals, but it missed a few cases.
The only remaining PEP8 violation (as far as I can see) is a too long line:
```python
method_name="backdoor.propensity_score_matching")
```
Which is 82 > 79 wide. However, this is not much and there does not seem to be a nice/pretty way to resolve this.
=> Fix styling issues in the readme

dowhy/causal_estimator.py
Changed string from of causal estimator when p=0.0 so instead it prin…ts p< (1/number of simulations). Might consider writing an attribute of CausalEstimator to output the p value so this is done in all circumstances.
Changed a line in test_significance that threw an exception when the estimated value was lower than the median estimate of the simulations.
Permit passing of number of simulations using the method_params parameter (useful because the default 1000 simulations for propensity score matching can take several minutes and because test_significance is not usually called manually).
=> Some changes in significance testing

dowhy/api/causal_data_frame.py
Hey Amit!
While we're getting the do op implemented, I thought I'd submit this WIP so we could start the conversation about how it's being set up. 
I'm following pandas' guidance on registering custom accessors here:
https://pandas.pydata.org/pandas-docs/stable/extending.html
Which sets it up nicely as an extension of the dataframe, with its own plot methods, so we don't have to override or weirdly rename (as I did in my package) the usual methods.
Let me know what you think!
Best,
A
=> Add dataframe api

dowhy/causal_estimator.py, dowhy/causal_identifier.py, dowhy/do_why.py, tests/causal_estimators/base.py, tests/causal_estimators/test_instrumental_variable_estimator.py, tests/causal_estimators/test_linear_regression_estimator.py, tests/causal_estimators/test_propensity_score_matching_estimator.py, tests/causal_estimators/test_propensity_score_stratification_estimator.py, tests/causal_estimators/test_propensity_score_weighting_estimator.py
* Updated the `CausalModel` to allow suppression of CLI prompts when an effect is determined to be unidentified using a kwarg. (Allows tests to run when specifying the backdoor set explicitly, and inconsistently with the graph).
* Added test coverage for IVs
* Updated the linear model test coverage to use the `linear_dataset` helper, instead of generating one from scratch.
* All tests pass
=> Add test coverage

dowhy/causal_identifier.py
Currently, in model.identify_effect, when not all common causes are observed but the proceed_when_unidentifiable flag is set, the logger outputs "All common causes are observed. Causal effect can be identified."
I changed this, so now the warning about unobserved confounders is still issued, followed by the information that we just ignore this and continue due to the flag.
=> Fix logger output when proceed_when_unidentifiable flag is set

dowhy/causal_estimators/instrumental_variable_estimator.py, tests/causal_estimators/base.py, tests/causal_estimators/test_instrumental_variable_estimator.py
Hi, this is great work and I hope that I can make some useful contributions! This is my first PR with 3 changes: 
1. FIx the IV estimate for the continuous variable case. My understanding is that the standard IV estimate for the ATE is R_{yz} / R_{xz}, where R_{yz} is the coefficient for Z in a regression of Y on Z and R_{xz} is the coefficient for Z in a regression of X on Z. This is equivalent to Cov(Y, Z) / Cov(X, Z). 
The current implementation for the IV estimate is mean(y*z) / mean(x*z) which will be close to Cov(Y, Z) / Cov(X, Z) when Y, X, Z have means close to 0. 
I compared the accuracy of the current IV estimate with the one obtained by dividing covariance and found that in 100 simulations of the linear dataset with beta = 1, the current IV estimate has more than 10% error in …
=> Improve iv

dowhy/api/causal_data_frame.py, dowhy/do_samplers/__init__.py
This is for surfacing import errors caused by the sampler file itself,
or other dependencies (such as PyMC3 for mcmc_sampler).
Instead of a confusing error message "xxxx is not an existing do
sampler", it actually shows what is the real Python module that is
missing.
Possibly fixing #55.
=> Friendlier message for sampler import error

dowhy/do_samplers/mcmc_sampler.py
`causal_model` will never be in `kwargs` because it has been changed to an explicit named parameter.
=> Fix mcmc_sampler causal_model argument

README.rst, dowhy/__init__.py, tests/causal_estimators/base.py, tests/causal_refuters/base.py
Added import to `dowhy.__init__.py` so that `CausalModel` can be imported directly from `dowhy`.
For example, with this change the [top README example](https://github.com/microsoft/dowhy#sample-causal-inference-analysis-in-dowhy) would start with
```
from dowhy import CausalModel
import dowhy.datasets
```
Does this address one of the cards in the "Bug fixes"?
Also, what do you think about changing `do_why.py` to something like `causal_model.py`?
=> Modified CausalModel import

dowhy/causal_estimator.py, dowhy/causal_refuter.py, dowhy/data_transformer.py, tests/test_causal_estimator.py, tests/test_causal_refuter.py, tests/test_data_transformer.py
This attempts to resolve #78
I added or modified these methods, to raise `NotImplementedError`
- `DimensionalityReducer.reduce`
- `CausalRefuter.refute_estimate`, because `CausalModel` assumes a refuter has this method
- `CausalEstimator._estimate_effect`, because it is referred to by `CausalEstimator.estimate_effect`
- `CausalEstimator.construct_symbolic_estimator`, because all of the classes in the `causal_estimators/` directory implement the method
I also made an attempt at writing tests to verify that subclasses need to implement these methods.
=> Adding a few placeholder methods

requirements.txt
This requirement might be causing the failing tests.
Should there be a version number on `econml`?
=> Added econml to requirements.txt

README.rst
The current link to the GML format for graphs goes to a Uni Passau page that says all projects are completed.
The suggested replacement link seems to be the new home of the GML format documentation: https://github.com/GunterMueller/UNI_PASSAU_FMI_Graph_Drawing
=> Fix deprecated link to GML

dowhy/causal_refuters/add_unobserved_common_cause.py, tests/causal_refuters/test_add_unobserved_common_cause.py
Added the ability to have a range of inputs for the linear coefficients used to show the effect of the unobserved confounder on the treatment and the outcome.
=> add multiple input capability for Unobserved Common Cause refutation

tests/causal_estimators/test_instrumental_variable_estimator.py, tests/causal_estimators/test_linear_regression_estimator.py, tests/causal_estimators/test_propensity_score_matching_estimator.py, tests/causal_estimators/test_propensity_score_stratification_estimator.py, tests/causal_estimators/test_propensity_score_weighting_estimator.py, tests/causal_estimators/test_regression_discontinuity_estimator.py, tests/causal_refuters/test_add_unobserved_common_cause.py, tests/conftest.py, tests/do_sampler/test_pandas_do_api.py
Add fixture to fix seed
- Add ```conftest.py``` to define seed
- Add fixture to class to fix random generation
The advantage of this lies with the fact it allows us to have reproducible tests. Seeding allows us to deal with the same set of random numbers.
=> Add seed for random numbers

dowhy/causal_refuter.py, dowhy/causal_refuters/add_unobserved_common_cause.py, dowhy/causal_refuters/bootstrap_refuter.py, dowhy/causal_refuters/data_subset_refuter.py, dowhy/causal_refuters/dummy_outcome_refuter.py, dowhy/causal_refuters/placebo_treatment_refuter.py, tests/causal_refuters/base.py, tests/causal_refuters/test_add_unobserved_common_cause.py, tests/causal_refuters/test_bootstrap_refuter.py, tests/causal_refuters/test_data_subset_refuter.py, tests/causal_refuters/test_dummy_outcome_refuter.py, tests/causal_refuters/test_placebo_refuter.py
This PR fixes the errors detected through testing. The most important being a data type check for adding the placebo data type in the placebo refuter. In addition, it adds a refuter that makes use of a dummy outcome. This allows us to test for the case in which we use instrumental variables to find the effect of the treatment on the outcome.
=> Clean up existing refuters and add Dummy Outcome Refuter

dowhy/causal_estimators/propensity_score_estimator.py, dowhy/causal_estimators/propensity_score_matching_estimator.py, dowhy/causal_estimators/propensity_score_stratification_estimator.py, dowhy/causal_estimators/propensity_score_weighting_estimator.py
A super class ```PropensityScoreEstimator```  has been added so as to remove the repetition of functionality and to prevent the recomputation of the propensity score each time. This will significantly improve the performance of the refuters as the covariates in all refuters excluding the placebo refuter will remain the same.
=> Add super class for propensity score estimators

dowhy/causal_estimators/causalml.py, tests/causal_estimators/test_causalml_estimator.py
Add 3rd party estimator from uber/causal ml by writing a wrapper in dowhy. This inherits the causal estimator class and currently runs only the Average Treatment Effect estimates.
=> add causalml estimator

tests/causal_refuters/base.py, tests/causal_refuters/test_bootstrap_refuter.py
Reduce the time taken by the bootstrap refuter, as it takes a major portion of the testing time.
=> increase tolerence and reduce sample size to speed up tests

tests/causal_estimators/test_causalml_estimator.py, tests/causal_refuters/test_add_unobserved_common_cause.py
We replace the download hack by using pytest.importor to check if CausalML is present.
=> Use pytest.importor to account for CausalMl dependency

docs/source/example_notebooks/dowhy-conditional-treatment-effects.ipynb, docs/source/example_notebooks/dowhy_simple_example.ipynb, dowhy/causal_estimators/econml.py, dowhy/causal_graph.py, dowhy/causal_model.py
* The key idea is to process such a variable as a common cause but also store its status as a effect modifier
* causal graph input also allows to specify an effect_modifier variable, because the desired variables on which effect needs to be separated out may be different from all effect modifiers
=> Support for when effect modifiers and common causes include common variables and compatibility with econml

dowhy/causal_estimator.py, dowhy/causal_estimators/linear_regression_estimator.py, dowhy/causal_refuters/dummy_outcome_refuter.py, dowhy/causal_refuters/placebo_treatment_refuter.py, tests/causal_estimators/base.py, tests/causal_estimators/test_linear_regression_estimator.py, tests/causal_estimators/test_propensity_score_matching_estimator.py, tests/causal_estimators/test_propensity_score_stratification_estimator.py, tests/causal_estimators/test_propensity_score_weighting_estimator.py, tests/causal_refuters/test_placebo_refuter.py
Major refactor of causal estimator: 
1. estimate now stores a reference to the estimator.
2. once a user has the estimate object, they can call to estimate CI, or std error, or test significance. Previously, they could not and had to call estimate_effect again.
3. Support for estimating standard error of the estimate.
=> Refactor causal_estimator to include standard error and allow repeated calls for CI, std error and test significance

dowhy/causal_estimators/linear_regression_estimator.py, dowhy/causal_model.py
The OLS print now follows the logging_level set in CausalModel.
Fixes #144
=> fixed logging bug for ols results

dowhy/causal_estimators/causalml.py
Convenience parameter: now can do estimate.cate_estimates to access CATE/ITE estimates from causaml estimators.
=> added cate_estimates param to output of causalml estimators

dowhy/causal_refuters/dummy_outcome_refuter.py, tests/causal_refuters/test_dummy_outcome_refuter.py
The earlier version of the dummy outcome refuter could not handle binary treatments. Thus, in this PR, we overcome this problem, by shifting a portion of the test treatment into the validation, so as to ensure, sufficient variation in the validation set. Furthermore, this has been generalized, to allow a user to sample a portion of the non-base categories.
=> Generalize dummy outcome refuter

README.rst
Resolves issue #205
The markup version of the readme that is displayed for the main page in this repo contains the following link:
Status code [404:NotFound] - Link: https://github.com/microsoft/dowhy/blob/master/docs/source/example_notebooks/dowhy_twins_example%20.ipynb
It should not have “%20” (space) in it.
The link should be: “https://github.com/microsoft/dowhy/blob/master/docs/source/example_notebooks/dowhy_twins_example.ipynb”
--
This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
Re-check this Repo via: Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fmicrosoft%2fdowhy
If you have any feedback on the information …
=> Fixed bad link in README file - Issue #205

dowhy/causal_identifier.py, dowhy/causal_model.py
A small refactoring of `CausalIdentifier.identify_backdoor`, which contained some duplicated code I though could be tidied up.
Only two methods for effect identification are now supported, and both of them propagate only to the `identify_backdoor`, The difference in logic is quite minor, in the sense that the one stops as soon as a valid adjustment set is found, and the other continues on to search the whole space.
The other difference was that exhaustive method was searching from the smallest adjustment set to the largest, while the other one was doing in reverse, from largest to smallest. It doesn't seem that important to me, but I could be wrong, so please let me know.
Tests are in general missing for causal identifiers, it would be a good idea to make some as a next step. :)
=> refactor identify backdoor to reduce code redundancy

dowhy/__init__.py, dowhy/causal_model.py, dowhy/causal_refuter.py, dowhy/causal_refuters/add_unobserved_common_cause.py, dowhy/causal_refuters/bootstrap_refuter.py, dowhy/causal_refuters/data_subset_refuter.py, dowhy/causal_refuters/dummy_outcome_refuter.py, dowhy/causal_refuters/placebo_treatment_refuter.py, tests/causal_refuters/base.py
When `basicConfig` is called, logging is set up automatically and unless
a `logging.NullHandler` instance is included with each call it becomes
very difficult to control logging from DoWhy. This change removes all
calls to `basicConfig` and adds a `NullHandler` to the root DoWhy
logger. Now, users of DoWhy can configure their logging preference
through something like `logging.config.dictConfig` with a reference to
`dowhy` in the `loggers` section of the configuration.
=> remove basic logging configuration

dowhy/causal_identifier.py
=> handle missing identifier method for getting backdoor variables

dowhy/causal_graph.py, dowhy/causal_identifier.py, tests/causal_identifiers/base.py, tests/causal_identifiers/example_graphs.py, tests/causal_identifiers/test_backdoor_identifier.py, tests/causal_refuters/base.py
The PR contains first batch of tests for the backdoor identification
At the moment, the method being tested is [CausalIdentifier.identify_backdoor](https://github.com/vojavocni/dowhy/blob/2970c7edddbc13dce267dc7b59a68aac0fe4a34e/dowhy/causal_identifier.py#L236).
From my perspective, this function should:
1. not return unobserved variables in backdoor sets
2. not return adjustment sets that induce bias
3. return all expected adjustment sets, at least the minimum sufficient adjustment sets 
TODO:
Three tests fail at the moment, one of them related to problems 1. and 2. and should be fixed by some refactoring of identify backdoor to not include unobserved variables and not adjust if there is no need.
The other two are related to this graph:
The possible adjustment sets are: (C), (B,C) and …
=> Backdoor identification tests

dowhy/causal_graph.py, dowhy/causal_model.py
As requested by sai_ on the discord server, it would be useful to be able to specify the size and file name of the figure produced by view_model.
I have added two parameters to view_model: `size` and `file_name`.
`size` allows the user to specify the desired size of the figure as a tuple `(x, y)` where `x` and `y` are the width and height in inches. This is consistent with the `figsize` argument in matplotlib. I have also ensured that this works with both matplotlib and pygraphviz.
`file_name` allows the user to specify the desired name of the png image (without including the `.png` extension). 
Example:
` model.view_model(layout="dot", size=(100, 20), file_name="my_causal_model")`
=> Added size and file_name parameters to view_model

dowhy/causal_estimator.py
Following issue #276, I have updated the `_estimate_confidence_intervals_with_bootstrap` method so that it now computes the **empirical** bootstrap. 
I also found a bug similar to issue #256; the confidence intervals computed using bootstrap assume that the treatment and control are 1 and 0 respectively. Therefore, if you want to compute the bootstrap confidence interval for a non-binary treatment e.g. `treatment_value=10` and `control_value=0`, the confidence intervals are still assuming `treatment_value=1` and hence are wrong.
I have added a fix for this issue by passing the specified treatment and control values to the estimators used in `_generate_bootstrap_estimates`. You can see the result by comparing the figures below:
These figures show the estimated causal effect (dark blue) and …
=> Changed bootstrap method to empirical and added treatment and control values to bootstrap generation.

dowhy/causal_estimator.py, dowhy/causal_graph.py, dowhy/causal_identifier.py, dowhy/causal_model.py
* Added a check for directed path from treatment to outcome
* If no such path exists, estimator is not called. Effect is zero by definition.
=> Bug fix: Return zero if there is no directed path from treatment to outcome

dowhy/causal_estimators/propensity_score_estimator.py
Right now all propensity score methods in dowhy throw an exception if the treatment data type is not boolean. This is far too restrictive, as underlying classifiers work just fine eg with integer 0 and 1 values, and even with floating point 0.0 and 1.0. 
resolves https://github.com/microsoft/dowhy/issues/361
=> Allow categories to be specified as non-booleans, as long as there are only two

dowhy/causal_model.py
This allows to use `method_params["init_params"]` with built-in DoWhy estimators, for example propensity_score_weighting_estimator, to supply eg custom propensity models, in a way consistent with how this works for EconML models.
Would resolve https://github.com/microsoft/dowhy/issues/345 and provide another way (consistent with how it's done for EconML estimators) of addressing https://github.com/microsoft/dowhy/issues/303
=> method_params["init_params"] for dowhy core estimators

dowhy/causal_model.py
Trivial graph without confounders does not raise a error.
Fixes #341
=> Fixed CausalModel bug on a trivial graph without any confounders

dowhy/causal_estimators/econml.py
Allow to call `effect`, `effect_inference`, and `shap_values` methods of wrapped EconML estimators by just passing in the whole dataframe, like you can with built-in estimators.
Makes it easier to use all estimators in a consistent fashion.
Took me a while to figure out that `_effect_modifier_names` is the only list of column names to use for this that will also work with metalearners, so would like to spare future users that effort
=> Call EconML estimate and shap_values methods in a way consistent with built-in estimators

dowhy/causal_estimators/generalized_linear_model_estimator.py, dowhy/causal_estimators/linear_regression_estimator.py, dowhy/causal_estimators/regression_estimator.py, dowhy/datasets.py, tests/causal_estimators/test_generalized_linear_model_estimator.py
Addresses #296 
By default, GLM models like logistic regression use the predicted score for computing E[Y|do(T)]. Adding flexibility to use the predicted class (using threshold of 0.5) for comparison with metalearner.
=> Allow using output class for binary outcome for do operation

.github/workflows/python-package.yml
This follows a recent change in causalml: https://github.com/uber/causalml/commit/939b962c54a4fbea835f686e2f82ab1d4e4bc8f8 and should fix dependency installation for tests.
=> Fix scikit-learn to 1.0.2

docs/source/gcm/user_guide/answering_causal_questions/attribute_distributional_changes.rst, docs/source/gcm/user_guide/answering_causal_questions/computing_counterfactuals.rst, docs/source/gcm/user_guide/answering_causal_questions/index.rst, docs/source/gcm/user_guide/answering_causal_questions/simulate_impact_of_interventions.rst, docs/source/gcm/user_guide/customizing_model_assignment.rst, docs/source/gcm/user_guide/introduction.rst
* Remove auto-assign. We can re-introduce auto-assigning causal models once the module was merged.
* Fix names of causal queries.
=> Adjust gcm documentation to current features

dowhy/gcm/ml/classification.py, dowhy/gcm/ml/regression.py
This avoids the user warning 
"Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble."
for users with a newer (>= 1.0) scitkit-learn version.
=> Skip experimental import when sklearn version is >= 1.0

dowhy/gcm/independence_test/kernel.py, dowhy/gcm/independence_test/kernel_operation.py
Now, the inputs are converted to numeric vectors and one specific approximation is used is used for all variables (instead of a different approximation per feature). This simplifies the customization of the utilized kernel approximation method and using the lambda function still offers the flexibility to concatenate different approximations into one function.
=> Revise and simplify approx_kernel_based

dowhy/gcm/independence_test/kernel.py
Changing scale_data by default from False to True and removing TODO entry.
=> Correcting default parameter in KCI test

dowhy/gcm/__init__.py, tests/gcm/test_auto.py
This PR adds the `auto` module to the `gcm` namespace, so that public artefacts of `auto` module can be invoked with `gcm.auto` prefix.
from dowhy import gcm
quality = gcm.auto.AssignmentQuality.GOOD
=> Add auto module to the main namespace

dowhy/gcm/__init__.py, dowhy/gcm/fcms.py, dowhy/gcm/influence.py, dowhy/gcm/ml/classification.py, tests/gcm/test_arrow_strength.py, tests/gcm/test_intrinsic_influence.py
This PR introduces the influence module which provides functionality for computing direct arrow strength in causal graphs and intrinsic causal influence.
It requires:
- https://github.com/py-why/dowhy/pull/452
to be merged first.
=> Introduce GCM-based influence module

dowhy/gcm/__init__.py, dowhy/gcm/feature.py, dowhy/gcm/util/general.py, tests/gcm/test_feature.py
This PR is depending on:
- https://github.com/py-why/dowhy/pull/433 
- https://github.com/py-why/dowhy/pull/438
Hence, feel free to skip modules `auto` and `confidence_intervals` when reviewing this.
=> Add GCM feature relevance module

dowhy/gcm/__init__.py, dowhy/gcm/validation.py, tests/gcm/test_validation.py
- Add method to reject graph structure based on (conditional) independence tests
- Add method to validate post non-linear model assignments (e.g., additive noise models) by testing for independence between residual and input
This PR is depending on:
- https://github.com/py-why/dowhy/pull/433
Hence the `auto` module should be reviewed only there.
=> Add gcm validation module

dowhy/causal_refuters/placebo_treatment_refuter.py, tests/causal_refuters/base.py, tests/causal_refuters/test_placebo_refuter.py
Give the placebo column the same index as the original data in case of categorical treatments to avoid later mismatches. Fixes #316.
As there were no tests yet for categorical treatment refutation, I decided to not add a full suite like in the case of binary/continuous treatment without more feedback. Am happy to add that, or a single dedicated test if desired.
=> Make sure placebo treatments are assigned consistently for categorical treatments

dowhy/gcm/anomaly.py, tests/gcm/test_anomaly.py, tests/gcm/test_anomaly_attribution.py
- Changing "anomaly_score_attributions" -> "attribute_anomaly_scores"
- Changing "conditional_anomaly_score" -> "conditional_anomaly_scores"
=> Rename gcm anomaly attribution functions for consistency

dowhy/causal_refuter.py, tests/test_causal_refuter.py
Makes sure the bootstrap test for refutation returns p-value corresponding to a two-sided not a one-sided test. Fixes #375
=> Two sided bootstrap test

dowhy/gcm/__init__.py, dowhy/gcm/whatif.py, tests/gcm/test_whatif.py
This PR introduces an API for estimating average causal effect on the target of two sets of interventions.
=> Add the API for estimating average causal effect using GCM

dowhy/causal_estimators/propensity_score_estimator.py, dowhy/causal_estimators/propensity_score_matching_estimator.py, dowhy/causal_estimators/propensity_score_stratification_estimator.py, dowhy/causal_estimators/propensity_score_weighting_estimator.py
For propensity score estimators, if `recalculate_propensity_score=False` and the `propensity_score_column` is missing, but the `propensity_score_function` exists, instead of failing, use the function to fill in the score, but without refitting the function.
Factor this logic out to the parent class `PropensityScoreEstimator`
=> Calculate propensity score from function without refitting, if possible

docs/source/example_notebooks/dowhy_simple_example.ipynb, dowhy/causal_refuter.py, dowhy/causal_refuters/data_subset_refuter.py, dowhy/causal_refuters/placebo_treatment_refuter.py, dowhy/causal_refuters/random_common_cause.py, requirements.txt
Hi @amit-sharma,
I've added parallelization to the random cause and the placebo refuter using `joblib`. 
Please let me know what you think of my implementation before I do the same with the rest. For example do you have a suggestion about how to avoid the inner function within `refute_estimate` which is not overly pretty imo. 
I also added to the Getting Started Notebook. Hope this is a good start for the feature.
=> Speed up refutation by parallelization

docs/source/_templates/versions.html
Forgot to update this in the previous PR.
=> Display main as main-branch in docs version selector

.github/workflows/build-and-publish-docs.yml, docs/source/conf.py
Title says it all. This addresses:
- https://github.com/py-why/dowhy/issues/588.
I'm using a fork of the original sphinxcontrib-googleanalytics package, which has a small change: https://github.com/petergtz/googleanalytics/commit/f32bcb8c0fb74bf284652b9a5c154337e20058b9
It looks like the original code does not call Google Analytics correctly. I'll see if I can contribute a change back upstream.
=> Add Google Analytics

dowhy/gcm/stats.py
The error for the model without inputs should be based on the difference of the observed values to the mean in the training data set. However, the mean of the test set was used instead.
=> Small correction in estimate_ftest_pvalue

README.rst
In the README file, the links to the GCM documentation page were broken due to recent versioning changes in the documentation. This PR fixes those.
Signed-off-by: Kailash Budhathoki <111277+kailashbuki@users.noreply.github.com>
=> Fix broken links to the gcm documentation page

.github/workflows/build-and-publish-docs.yml, poetry.lock, pyproject.toml
https://github.com/py-why/dowhy/security/dependabot/1
* Updates nbconvert to 7.0rc3 & mistune to a safe version
* Move documentation-generation dependencies into devDependencies area
* Run `poetry update` for dependency refresh
=> Add dependency to resolve security alert

dowhy/causal_graph.py, dowhy/causal_identifier.py, tests/causal_identifiers/base.py, tests/causal_identifiers/example_graphs.py, tests/causal_identifiers/test_backdoor_identifier.py
This PR adds a new estimand_type="nonparametric-cde" and associated identification method to compute the controlled direct effect. 
The estimation can still be handled using standard backdoor estimators since the estimand is always a conditional expectation.
=> Add support for controlled direct treatment effect

tests/test_notebooks.py
Remove dowhy_causal_discovery_example.ipynb from advanced tests that are run daily.  It is failing due to a cdt install problem.  Temporarily disabling since we are switching CD implementations.
Signed-off-by: emrekiciman <emrek@microsoft.com>
=> Remove dowhy_causal_discovery_example from tests

docs/source/example_notebooks/dowhy_ranking_methods.ipynb
This fixes failures like this one: https://github.com/py-why/dowhy/actions/runs/3301256767/jobs/5446526501#step:7:133
=> Fix syntax error in dowhy_ranking_methods notebook

docs/source/example_notebooks/dowhy_lalonde_example.ipynb, docs/source/example_notebooks/dowhy_refutation_testing.ipynb, docs/source/example_notebooks/lalonde_pandas_api.ipynb
This was copied from [wayfair/pylift](https://github.com/wayfair/pylift/blob/5afc9088e96f25672423663f5c9b4bb889b4dfc0/examples/Lalonde/Lalonde_sample.ipynb?short_path=b1d451f#L94-L99) and uses the information provided on https://users.nber.org/~rdehejia/nswdata2.html
This should fix at least part of the nightly failing tests, such as this one: https://github.com/py-why/dowhy/actions/runs/3301256767/jobs/5446526501#step:7:234.
=> Load Lalonde dataset natively with Python

dowhy/causal_refuters/placebo_treatment_refuter.py
Fix for bug reported in issue #699 
According to numpy docs: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html the `high` parameter is exclusive, meaning the highest value is never used in the `new_treatment` (in binary treatments it means this generates only 0's). Adding `+1` should resolve this. 
Signed-off-by: Andres Morales <andresmor@microsoft.com>
=> fix placebo treatment refuter randint call

dowhy/gcm/auto.py, dowhy/gcm/ml/regression.py, tests/gcm/ml/test_regression.py
Adding ProductRegressor to gcm auto assignment
This model simply takes the product of the inputs.
=> Adding ProductRegressor to gcm auto assignment

poetry.lock, pyproject.toml
Adding extra for econml to prevent it from being installed by default on a new project. 
Marking pydot and pygraphviz as optional to match the README documentation.
=> Mark econml, pydot, and pygraphviz as extras

poetry.lock, pyproject.toml
The gcm module will heavily rely on the independence tests in the causal-learn package, i.e., it cannot be optional.
=> Adding causal-learn as (required) dependency

dowhy/gcm/independence_test/__init__.py, dowhy/gcm/independence_test/kernel.py, dowhy/gcm/independence_test/kernel_operation.py, tests/gcm/independence_test/test_kernel.py
The causal-learn package provides more sophisticated implementations of the kernel independence tests. Instead of reimplementing it, we utilize the existing functions from causal-learn instead.
=> Replace HSCI and KCI with causal-learn package functions

pyproject.toml
By declaring these markers ahead-of-time we avoid some warnings during test runs.
=> Add pytest markers for "focused" and "notebook"

tests/gcm/test_whatif.py
To avoid flaky tests.
This failed here: https://github.com/py-why/dowhy/actions/runs/3343835339/jobs/5537478998#step:9:196
=> Make unit test on intervention less strict

.github/workflows/advanced-on-demand.yml, .github/workflows/ci.yml, .github/workflows/nightly-tests.yml, .github/workflows/python-publish.yml, tests/test_notebooks.py
This PR restores the notebook tests to normal CI that were relegated to the nightly-advanced test suite.
=> Restore Notebook Tests in Regular CI

poetry.lock, pyproject.toml
=> Upgrade xgboost

docs/source/user_guide/gcm_based_inference/introduction.rst
* Remove bibtex from GCM introduction. This is covered in docs/source/cite.rst.
* Add 'Typical usage' section in GCM introduction
=> Overhaul GCM introduction

dowhy/gcm/distribution_change.py
This avoids a future deprecation warning.
=> Use concat instead of append for pandas in distribution change

docs/generate_docs.sh, docs/source/_templates/versions.html, docs/source/conf.py
* Determine tag-list and current version in generate_docs and pass to Python
* Remove static legacy versions in versions.html; these will be provided in the tag-list.
Note: I'm waiting on some build output to verify the rendered result 🤞 (EDIT: looks okay)
=> Restore Version Selector into Build

dowhy/gcm/__init__.py, dowhy/gcm/unit_change.py, tests/gcm/test_unit_change.py
- Added two new APIs for attributing unit-level output changes when the mechanism does not change.
Signed-off-by: Kailash <111277+kailashbuki@users.noreply.github.com>
=> Add APIs for attributing unit change without a mechanism change

docs/source/conf.py
This is broken, when the path of the current page is nested.
=> Fix links to older doc versions

dowhy/gcm/util/plotting.py, dowhy/gcm/util/pygraphviz.py, tests/gcm/util/test_plotting.py
Before, the given causal_strength dictionary was modified within the plotting function, which also impacted the original object. Now, a copy is created internally.
=> Fix issue in gcm plotting with modifying causal_strength object

dowhy/causal_identifier/efficient_backdoor.py, tests/causal_identifiers/example_graphs_efficient.py
Hi there. Sara Taheri pointed out the [optimaladj](https://github.com/facusapienza21/optimaladj) package was giving the wrong answer in the following simple example:
```
treatment = 'T'
outcome = 'Y'
L = []
N = ['T', 'Z1', 'Z2', 'Z3', 'M1', 'M2', 'Y']
G = CausalGraph()
G.add_edges_from([('Z1', 'Z2'),
('Z1', 'T'),
('Z2', 'Z3'),
('Z3', 'Y'),
('T', 'M1'),
('M1','M2'),
('M2', 'Y')])
G.ignore(treatment, outcome, L, N)
```
The output should be M1, M2, and it is only M2. 
Since doWhy has the same implementation as optimaladj, the analogous error in this package. The error is due to a bug in the method that constructs the forbidden set, specificially [here](https://github.com/py-why/dowhy/pull/777/files#diff-bf4ee8953848928b1341a76af189487030c02acdc46a071183112115c008856aL120). The problem is …
=> Bug in ignore method of EfficientBackdoor class

docs/source/code_repo.rst, docs/source/dowhy.causal_identifier.rst, docs/source/dowhy.causal_refuters.rst, docs/source/dowhy.gcm.independence_test.rst, docs/source/dowhy.gcm.ml.rst, docs/source/dowhy.gcm.rst, docs/source/dowhy.rst, docs/source/dowhy.utils.rst
This PR includes the release notes for v0.9
Signed-off-by: Amit Sharma <amit_sharma@live.com>
=> [Version Bump v0.9] Release notes and updated docstrings

pyproject.toml
PyPI is picking up an incorrect URL for the latest release. This won't fix the pypi issue until the next release though.
Signed-off-by: Amit Sharma <amit_sharma@live.com>
=> Updated correct url for dowhy in pyproject

.github/workflows/advanced-on-demand.yml, .github/workflows/ci-install.yml, .github/workflows/ci.yml, .github/workflows/nightly-tests.yml, .github/workflows/python-publish.yml, poetry.lock, pyproject.toml, tests/gcm/ml/test_autogluon.py, tests/gcm/test_auto.py
* Add Python version condition on `autogluon-tabular`.
* Remove `autogluon-tabular` from dev-dependencies to add Python 3.10 to our builds.
**Note**: `autogluon-tabular` has a dependency constraint on `scikit-learn` of `<1.2.0`. So we're able to advance `scikit-learn` past `1.0.2`, but not to the most recent version.
**Note**: `econml` has a transitive dependency on `numba`, which requires Python `<3.11`, and our `tensorflow` dev-dep has a range of `<3.11`.
=> Add Python 3.10 support

dowhy/gcm/util/plotting.py, dowhy/gcm/util/pygraphviz.py, tests/gcm/util/test_plotting.py
Added an optional parameter `colors` when plotting a graph. This can be used to color individual nodes or edges in the graph. E.g. 
```
import networkx as nx
from dowhy.gcm.util import plot
plot(nx.DiGraph([('X0', 'X1'), ('X1', 'X2')]), colors={('X0', 'X1'): 'red', 'X2': 'green'})
```
generates a plot where the edge between X0 and X1 is colored red and the node X2 is colored green. This works with both plotting via pygraphviz and networkx.
Signed-off-by: Elias Eulig <eeulig@amazon.com>
=> Add color option to graph plotting

LICENSE
Post moving to the py-why org, the dowhy license should include copyright of "pywhy contributors".
This PR changes the text in MIT license.
=> Change copyright owner to PyWhy contributors in LICENSE

docs/source/contributing/contributing-code.rst
During december this option was removed from the pyproject.toml. As the current instruction throws an error, it might discourage unexperienced first-time contributors from pursuing, hence the clean up.
Signed-off-by: Michael <marien.mich@gmail.com>
=> removed causal-ml from poetry setup instructions

docs/source/index.rst
This is mainly for consistency, so we can get better aggregate metrics in Google Analytics. For users it probably makes no difference.
Signed-off-by: Peter Goetz <pego@amazon.com>
=> Point user guide link to user guide instead of intro

.github/workflows/advanced-on-demand.yml
This is required to have all necessary dependencies and it also makes this workflow consistent with the nightly tests. Otherwise the on-demand tests break.
Signed-off-by: Peter Goetz <pego@amazon.com>
=> Add docs deps in advanced-on-demand workflow

dowhy/causal_estimator.py, dowhy/causal_model.py
While investigating a [question on discord](https://discord.com/channels/818456847551168542/1068535649566724116/1068892182683070524) I saw that these arguments were not being passed to the constructed estimator anymore.
@amit-sharma Not sure if this is correct. Feel free to let me know if there is a better way to do this.
=> Bug fix: Missing use of arguments in estimate effect 

dowhy/causal_model.py
Current rendering of variables is off in https://www.pywhy.org/dowhy/v0.9.1/dowhy.html#module-dowhy.causal_model
Signed-off-by: Michael <marien.mich@gmail.com>
=> fixed sphinx docstring format for causal model

dowhy/gcm/shapley.py
=> Change np.int to np.int32 in shapley.py

dowhy/gcm/__init__.py, dowhy/gcm/feature.py, dowhy/gcm/feature_relevance.py, tests/gcm/test_feature_relevance.py
The new name 'feature_relevance' will help clarify the type of functionality to expect from the module.
=> Renaming gcm feature.py module to feature_relevance.py

dowhy/gcm/util/general.py, tests/gcm/util/test_general.py
Before, one dimension is dropped in the encoding. However, this requires to assume that there are no unknown categories, since these would be mapped to a zero vector as well, which then coincides with one of the categories. Now, there are as many dimensions as categories, which allow to map unknown categories to a zero vector.
=> Change one-hot-encoding behaviour in gcm module

tests/gcm/test_arrow_strength.py, tests/gcm/test_auto.py, tests/gcm/test_distribution_change.py, tests/gcm/test_divergence.py, tests/gcm/test_feature_relevance.py, tests/gcm/test_graph.py, tests/gcm/test_noise.py, tests/gcm/util/test_general.py
- Add tests for arrow strength estimation in a setting there graph and models are misspecified
- Add tests for checking linear relationships
- Add tests to verify that default (auto) fitted models are accurate enough to capture the data statistics
- Add tests for mechanism change test
- Add tests for the `_noise` module, such as reconstructing the noise or estimating data based on given noise
- Add tests for some general utility functions such as shaping a numpy array into 2d
- Remove test for feature relevance with confidence intervals, since the confidence interval method and feature relevance method are tested separately
=> Add and remove some unit tests in gcm module

dowhy/gcm/shapley.py, tests/gcm/test_shapley.py
- Shapley config parameter now clearly distinguishes between num_subset_sampling and num_permutations
- Using a quasi-random sequence generator now to improve uniform sampling of permutation. This should improve convergence (i.e., more accurate estimations)
- Fix bug in early stopping where one can get negative percentages and, thus, the estimator would falsely stop too early.
- Early stopping criteria is now applied to the change of each Shapley value individually instead of the average change. This should ensure less variance in the results between two runs and more accurate results.
- Change minimum change in percentage threshold to 0.05 by default for early stopping. This balances out the potential slower runtime from the change above.
=> Revise gcm Shapley estimator

dowhy/gcm/influence.py
This should decrease runtime without much loss of accuracy.
=> Change default parameter of the ICC method

CONTRIBUTING.md
The links from the Contributing Guide to the license are broken because the LICENSE file doesn't have an extension.
=> Fix broken links to license

dowhy/gcm/anomaly.py
Decrease the default number of distribution samples. This significantly speeds up the calculation without losing much accuracy.
=> Change default parameters in attribute_anomalies

dowhy/gcm/influence.py, tests/gcm/test_intrinsic_influence.py
Before, it was only possible to estimate intrinsic causal contributions with respect to the distribution. This new method allows to estimate the influences of upstream nodes on a particular observation of a target node. As for now, this requires that all models are invertible with respect to the noise.
=> Add method to estimate ICC for single samples

dowhy/datasets.py
Fix issue with `dowhy.datasets.dataset_from_random_graph()` where the dataset is not generated at random. Previously Numpy random seed was hard set to 100 within the function. I have now also allowed for `random_seed` being selected if not passed into function as a parameter.
=> Fix #832. Randomness by default now.

docs/source/dowhy.gcm.ml.rst, dowhy/gcm/auto.py, dowhy/gcm/ml/__init__.py, tests/gcm/ml/test_autogluon.py
There was a typo "autolguon" -> "autogluon"
=> Correct import name for autogluon

dowhy/datasets.py
I have fixed the scalar issue and also resolved the redundancy between `num_treatments` and `beta` by making `num_treatments` optional and inferable from beta. If `num_treatments` is provided, beta is silently recycled to `num_treatments` as before.
=> (Fix #876) dataset: Allow for non-scalar beta and make num_treatments optional

docs/source/example_notebooks/dowhy_causal_discovery_example.ipynb, docs/source/example_notebooks/dowhy_optimize_backdoor_example.ipynb, docs/source/example_notebooks/gcm_supply_chain_dist_change.ipynb, dowhy/causal_graph.py, dowhy/causal_identifier/backdoor.py, dowhy/gcm/_noise.py, dowhy/gcm/fitting_sampling.py, dowhy/gcm/uncertainty.py, dowhy/gcm/validation.py, dowhy/graph_learners/cdt.py, poetry.lock, pyproject.toml
The autogluon models can still be used with DoWhy, but it is not listed as an optional dependency anymore to reduce the number of restrictions on other packages.
=> Removing autolguon as optional dependency

dowhy/gcm/influence.py
Increased the number of baseline samples from 1000 to 2000. This should give more accurate results without impacting the runtime too much.
=> Change default parameter in the intrinsic_causal_influence method

dowhy/utils/plotting.py
Pygraphviz was intended to be an optional dependency, but it was imported for typing, thus making it a hard dependency. This hard dependency has now been removed.
=> Fix an import issue with pygraphviz

dowhy/causal_estimators/distance_matching_estimator.py
Enabled `float` and `int` as possible binary treatment encoding options in class `DistanceMatchingEstimator`. 
Additionally, re-formatted some of the doc strings to match the `flake8` requirements.
Other estimators discussed in https://github.com/py-why/dowhy/issues/772 already accepted `int`, `bool`, and `float` types and I did not change them.
=> Enabled float and int as possible binary treatment encoding options in class `DistanceMatchingEstimator`

dowhy/causal_estimators/econml.py, dowhy/causal_graph.py, dowhy/causal_model.py, tests/causal_estimators/test_econml_estimator.py
Fixes #890 
The CATE estimates array structure is like this:
@kbattocchi Is the estimates array returned by EconML nested like this? Does the structure look good?
=> Fix to ensure that all CATE estimates are returned

tests/gcm/independence_test/test_kernel.py
This test became irrelevant, since we are now using an implementation for KCI from a different package.
=> Remove a independence test unit test

tests/gcm/independence_test/test_kernel.py, tests/gcm/independence_test/test_regression.py
Since we now use the KCI implementation of an external package, we don't need these tests anymore.
This commit also makes a regression_based unit test less flaky.
=> Remove obsolete unit tests for KCI

poetry.lock, pyproject.toml
Statsmodels 0.14.0 is out and the current specifications don't allow for it.
Fails with
> Note: This error originates from the build backend, and is likely not a problem with poetry but with econml (0.13.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "econml (==0.13.0)"'.
Opened https://github.com/py-why/EconML/issues/798
=> Relax statsmodels dependency

dowhy/causal_identifier/__init__.py
causal identifier __init__.py now gives access to construct_iv_estimand, construct_frontdoor_estimand, and construct_backdoor_estimand functions available on auto_identifier.py
=> Extend causal identifier init

dowhy/gcm/shapley.py, poetry.lock, pyproject.toml
I was installing dowhy with our intern, and noticed that the sphinx dependencies were being pulled in. These should only be installed when building the docsite.
=> Move sphinx_design to docdeps

.github/workflows/docs-release.yml
Post release, docs-release.yml failed because econml was not installed.
=> Update docs release actions file to include econml in build

.github/workflows/docs-release.yml
I believe that this change to the documentation publication workflow should allow it to be run manually, in case the automatic process failed when a new release was created.
=> Enable manual creation of docs for a release

dowhy/utils/plotting.py
Before, we only caught ImportErrors. However, it can also be that the module has not been installed at all, which would lead to a ModuleNotFoundError instead.
=> Add handling of ModuleNotFoundError in plotting function

dowhy/causal_estimator.py
The change to "dummy_outcome" was lost in the refactor, because the refactor extracted the outcome variable from target_estimand. Now creating a copy of the target_estimand.
Fixes #1006
=> Fix p-value error for estimator significance: Updated the outcome variable to "dummy_outcome"

dowhy/gcm/_noise.py, dowhy/gcm/fitting_sampling.py, tests/gcm/test_noise.py
Addresses https://github.com/py-why/dowhy/issues/1020
The issue was that pandas versions prior to 2.0 correctly inferred the data type from an input like `np.array([[2.0]], dtype=object)` (even though the dtype is object). In contrast, pandas 2.0 does not make this inference. However, the two-dimensional value was unintentional in the first place. It should be `np.array([2.0], dtype=object)`, which is then correctly handled across all versions.
=> Fix issues with pandas 2.0 in GCM module

dowhy/gcm/influence.py, tests/gcm/test_intrinsic_influence.py
Previously, only the 'exact' model could be used in the sample-wise ICC function. Now, there is a "prediction_model" parameter, similar to the population-based ICC function, that allows for the passing of a pre-defined prediction model.
=> Add prediction_model parameter to ICC sample function

dowhy/causal_model.py
Changing the value from "dot" to None. The current default value requires the dot extension to be installed. However, if it is not installed, an error is raised. By default, this should not happen since it is an optional dependency.
Addresses: https://github.com/py-why/dowhy/issues/1041
=> Change default value of layout in view_model of CausalModel

tests/gcm/test_unit_change.py
Turning off the parallelization by setting the `n_jobs` parameter to `1`, since this can occasionally cause a timeout error in the unit tests.
=> Fix timeout issues in tests for the unit_change module

dowhy/graph.py
The graph module uses Protocols, which have been natively supported since Python 3.8 (the required minimum version for DoWhy). To support Protocols in earlier Python versions, an extension provided Protocol support. However, this extension can cause compatibility issues with newer versions of other packages. With this change, DoWhy now uses the Protocol implementation that has been available since Python 3.8.
=> Change use of Protocol from typing instead of typing_extension

dowhy/causal_estimators/two_stage_regression_estimator.py, tests/causal_estimators/test_two_stage_regression_estimator.py
Fixes #616 
The refactor in v0.9 had introduced this bug.
=> Fix frontdoor estimation bug

dowhy/gcm/auto.py, tests/gcm/test_auto.py
Before, the auto assignment threw an error when there are too few samples available from one class due to the cross validation. Now, using `StratifiedKFold` makes sure that the classes are balanced in the folds.
=> Fix issue with auto assignment with imbalanced classes

dowhy/gcm/ml/regression.py, tests/gcm/test_ml.py
Before, when creating a linear regressor with fixed parameters, the parameters would be overridden upon fitting to data. Now, the parameters remain fixed.
=> Fix issue with linear regressor with fixed parameters

README.rst, docs/source/cite.rst, dowhy/gcm/__init__.py, dowhy/gcm/anomaly_scorers.py, dowhy/gcm/causal_mechanisms.py, dowhy/gcm/causal_models.py, dowhy/gcm/confidence_intervals.py, dowhy/gcm/confidence_intervals_cms.py, dowhy/gcm/density_estimators.py, dowhy/gcm/distribution_change.py, dowhy/gcm/divergence.py, dowhy/gcm/falsify.py, dowhy/gcm/feature_relevance.py, dowhy/gcm/fitting_sampling.py, dowhy/gcm/independence_test/kernel.py, dowhy/gcm/independence_test/kernel_operation.py, dowhy/gcm/influence.py, dowhy/gcm/ml/classification.py, dowhy/gcm/ml/regression.py, dowhy/gcm/shapley.py, dowhy/gcm/stats.py, dowhy/gcm/stochastic_models.py, dowhy/gcm/uncertainty.py, dowhy/gcm/util/general.py, dowhy/gcm/validation.py, dowhy/gcm/whatif.py
Also slightly change citation hint.
=> Remove 'experimental' disclaimer from GCM modules

tests/gcm/test_unit_change.py
The build sometimes randomly fails due to a timeout issue in the unit tests of the unit change methods of the GCM module. While this only happens in the github builds, this is most likely due to the prallelization of the underlying RandomForestRegressors being fitted.
=> Address issue with timeouts in unit change tests

dowhy/gcm/anomaly_scorers.py, tests/gcm/test_anomaly_scorers.py
NaN values are now correctly counted when estimating the anomaly score.
=> Fix handling of NaN values in MedianCDFQuantileScorer

dowhy/utils/plotting.py, tests/utils/test_plotting.py
If the confidence intervals are misspecified, e.g., greater lower bound than upper bound, the method threw an error before. This, however, can sometimes happen due to precision errors in some algorithms and lead to random build fails. This change fixes the issue and ignores invalid intervals accordingly.
=> Fix issue in bar_plot with misspecified confidence intervals

dowhy/gcm/ml/classification.py, tests/gcm/ml/test_classification.py
Before, the Support Vector Classifier did not produce probabilities, which are required for different algorithms in the GCM module. This changes the 'probability' parameter to True.
=> Change default parameter of SVC model in the GCM module

docs/source/user_guide/modeling_gcm/model_evaluation.rst, dowhy/gcm/model_evaluation.py, tests/gcm/test_model_evaluation.py
In addition to CRPS and depending on the node data type, it now also reports the MSE, NMSE, R2 and F1 score.
=> Extend GCM model evaluation by additional metrics

dowhy/causal_estimators/econml.py, tests/causal_estimators/test_econml_estimator.py
Fixes #1038.  
In v0.10, the user is expected to provide only the effect modifiers columns, which can cause issues if the order of effect modifiers is not correct. 
So we revert to v0.8 behavior where the user is only expected to pass the dataframe.
=> auto identify the effect modifier columns for `effect' method for EconML estimators

docs/source/user_guide/modeling_gcm/model_evaluation.rst, dowhy/gcm/__init__.py, dowhy/gcm/auto.py, dowhy/gcm/causal_mechanisms.py, dowhy/gcm/fitting_sampling.py, dowhy/gcm/model_evaluation.py, dowhy/gcm/util/general.py, tests/gcm/test_auto.py, tests/gcm/test_fcms.py, tests/gcm/test_model_evaluation.py, tests/gcm/test_whatif.py, tests/gcm/util/test_general.py
- Add new Discrete Additive Noise Model class that enforces the outputs to be discrete. This should help in generating more consistent data.
- As part of this, revised the auto assignment function and revised its docstring.
- Revise the auto assignment summary.
- Revise the evaluation summary.
=> Add explicit support for discrete ANMs and some revisions

README.rst
The compiled HTML versions of a notebook is better to get an understanding of the outputs etc.
=> Change readme notebook links to compiled HTML versions

dowhy/causal_graph.py, dowhy/causal_model.py, dowhy/gcm/causal_models.py, tests/test_causal_model.py
Before, the causal graphs between the GCM and CausalModel part required some additional work to be converted. Now, a GCM can be used to initiate a CausalModel or CausalGraph and vice versa.
This should improve the interoperability and makes it easier to switch between the functionalities.
However, after the change https://github.com/py-why/dowhy/pull/943, this compatibility should be deprecated until the CausalModel and CausalGraph object is removed completely.
=> Add compatibility between GCM and CausalModel class

.github/workflows/python-publish.yml, pyproject.toml
On version tag creation, the python publish workflow failed. 
This PR modifies the workflow so that it can be run again and it can fetch the previous tags. 
Also it modifies pyproject.toml such that the version number returned by `poetry-dynamic-versioning`  is a simple string that is exactly the tag version number.
Based on: https://github.com/mtkennerly/poetry-dynamic-versioning/issues/78
=> Fixing python publish workflow to run after version tag is created

dowhy/gcm/__init__.py, dowhy/gcm/equation_parser.py, tests/gcm/test_equation_parser.py
- This feature will enable user to write custom equations for each and node and get a causal model back with causal mechanisms assigned.
- The Usage is mainly targeted for when the function/relationship model between nodes is known and allows user to specify it in a equation form as demonstrated below - 
```
X = empirical()
Y = 12*exp(X) + halfnorm()
Z = 3*Y + empirical()
```
- List of Supported functions for specifying parent-child relationships - [here](https://numexpr.readthedocs.io/en/latest/user_guide.html#supported-functions)
- List of Supported functions for specifying noise models [here](https://docs.scipy.org/doc/scipy/reference/stats.html#continuous-distributions)
=> Equation-to-graph

tests/gcm/test_shapley.py
It seems there is a problem with one of the unit tests that explicitly rely on timeouts. Removing this test to avoid these issues in builds.
=> Potential fix for timeout errors in unit tests

tests/causal_estimators/base.py, tests/causal_estimators/mock_external_estimator.py, tests/causal_estimators/test_causalml_estimator.py, tests/causal_estimators/test_econml_estimator.py, tests/causal_estimators/test_generalized_linear_model_estimator.py, tests/causal_estimators/test_instrumental_variable_estimator.py, tests/causal_estimators/test_linear_regression_estimator.py, tests/causal_estimators/test_propensity_score_matching_estimator.py, tests/causal_estimators/test_propensity_score_stratification_estimator.py, tests/causal_estimators/test_propensity_score_weighting_estimator.py, tests/causal_estimators/test_regression_discontinuity_estimator.py, tests/causal_estimators/test_two_stage_regression_estimator.py, tests/causal_refuters/base.py, tests/causal_refuters/test_add_unobserved_common_cause.py, tests/causal_refuters/test_bootstrap_refuter.py, tests/causal_refuters/test_data_subset_refuter.py, tests/causal_refuters/test_dummy_outcome_refuter.py, tests/causal_refuters/test_placebo_refuter.py, tests/gcm/test_noise.py, tests/gcm/test_stochastic_models.py, tests/gcm/test_whatif.py
The TestEstimator and TestRefuter were falsely interpreted as unit test classes due to their "Test" prefix.
=> Rename classes in test folder

tests/causal_estimators/mock_external_estimator.py
This should fix the import error for the causal estimator unit tests.
=> Fix missing import for unit test

dowhy/causal_model.py, tests/test_causal_model.py
Add an accessor and comments explaining the expected lifecycle and use of CausalEstimator objects stored in the CausalModel._estimator_cache dict. Accessor function gains test coverage and slightly simplifies logic via use in CausalModel.estimate_effect().
See issue https://github.com/py-why/dowhy/issues/1071
=> Add accessor and comments about CausalModel's CausalEstimator cache.

dowhy/causal_estimators/regression_estimator.py, dowhy/utils/encoding.py, tests/utils/test_encoding.py
Fix bug with consistency of RegressionEstimator one-hot encoding by switching from pandas get_dummies to sklearn OneHotEncoder.
See issue https://github.com/py-why/dowhy/issues/1111
=> Fix bug with consistency of RegressionEstimator one-hot encoding

docs/source/user_guide/intro.rst
=> Update intro.rst 

dowhy/gcm/independence_test/kernel.py, dowhy/gcm/independence_test/regression.py, dowhy/gcm/model_evaluation.py, dowhy/gcm/stats.py, tests/gcm/test_stats.py
This uses an improved version of the "twice the average" rule following recent results from M. Gasparini, R. Wang, and A. Ramdas, *Combining exchangeable p-values*, arXiv 2404.03484, 2024.
This new method is now used by default when merging p-values. Accordingly, the quantile based method was renamed to be more consistent with the naming pattern.
=> Add new statistical method to merge p-values

dowhy/causal_estimators/distance_matching_estimator.py, dowhy/causal_estimators/econml.py, dowhy/causal_refuters/add_unobserved_common_cause.py, dowhy/causal_refuters/bootstrap_refuter.py, dowhy/causal_refuters/data_subset_refuter.py, dowhy/causal_refuters/dummy_outcome_refuter.py, dowhy/causal_refuters/evalue_sensitivity_analyzer.py, dowhy/causal_refuters/placebo_treatment_refuter.py, dowhy/causal_refuters/random_common_cause.py
Fixes #1028
When calling `fit` inside refutation methods, the `effect_modifier_names` was passed without name. Now it is a named parameter and avoids getting mixed up with other parameters. 
Also generalized `econml_fit_params` to `fit_params` since other methods can also have `fit_params`.
=> Fixes #1028: Updated argument calling for refutation methods 

docs/source/example_notebooks/dowhy_causal_discovery_example.ipynb
The variable `model` was used for both Lingam and CausalModel in the notebook (https://www.pywhy.org/dowhy/main/example_notebooks/dowhy_causal_discovery_example.html) which I found a bit confusing when playing around. This PR renames one of the uses of the variable `model` into `model_lingam`.
Related PR: https://github.com/py-why/dowhy/issues/859
=> Minor variable name fix in documentation

dowhy/gcm/stats.py
May fix:
```
dowhy/gcm/stats.py:4: PendingDeprecationWarning: Importing from numpy.matlib is deprecated since 1.19.0. The matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray. 
from numpy.matlib import repmat
```
I couldn't run the tests on my laptop because it's not powerful enough.
=> Use numpy tile instead of matrix

README.rst, docs/source/contributing/contributing-code.rst, docs/source/getting_started/install.rst
Modify graphviz installation command in README.rst, contributing-code.rst, and install.rst. Solves https://github.com/py-why/dowhy/issues/1172
=> Modify graphviz installation command

dowhy/gcm/stats.py, tests/gcm/test_stats.py
Before, a single p-value still got adjusted using the 2 * ... formula, which led to an unnecessary adjustment.
=> Small correction of average p-value merger

dowhy/gcm/anomaly.py, dowhy/gcm/distribution_change.py, dowhy/gcm/influence.py, dowhy/gcm/model_evaluation.py, tests/gcm/test_stats.py
NumPy matlib has been deprecated. Replacing the usage accordingly.
=> Replacing numpy repmat with tile

dowhy/causal_estimators/propensity_score_matching_estimator.py
This PR addresses this [issue](https://github.com/py-why/dowhy/issues/935) by introducing vectorized operations instead of the existing for-loops. This should speed up operations for large datasets.
This PR is a work in progress, and the remaining tasks include:
=> Vectorize operations for propensity score matching 

dowhy/gcm/anomaly_scorers.py, tests/gcm/test_anomaly.py, tests/gcm/test_anomaly_scorers.py, tests/gcm/test_ml.py
This is very closely related to the RescaledMedianCDFQuantileScorer but a statistically more well-defined approach. However, it is also slightly more conservative for small sample sizes. Furthermore, it changes the way equal samples are counted in MedianCDFQuantileScorer by also including the test sample itself. This prevents a p-value of 0.
=> Add RankBasedAnomalyScorer as an anomaly scorer

docs/source/user_guide/modeling_gcm/draw_samples.rst, docs/source/user_guide/modeling_gcm/model_evaluation.rst, dowhy/gcm/falsify.py
A super minor PR, just correcting three instances of "Falsification" being mis-spelled as "Falsificaton".
=> Fix typos, 'Falsificaton' -> 'Falsification'

docs/source/user_guide/modeling_gcm/estimating_confidence_intervals.rst
I believe that this was a copy-paste error, as the `data_old` variable was used in an example above.
=> docs: small fix in user guide

dowhy/gcm/model_evaluation.py, dowhy/gcm/stats.py, tests/gcm/test_stats.py
The method merges p-values by taking the minimum of the adjusted p-values. This then represents a p-value for a global hypothesis.
=> Add new method to merge p-values using FDR

dowhy/gcm/causal_models.py
Before, when a causal graph had causal mechanisms assigned, they were also used when creating a new GCM object based on it. Now, they are removed (from a copied version of the graph) if the new flag is set to True.
=> Remove existing causal mechanisms when creating GCM

dowhy/gcm/influence.py
Taking less samples to estimate ICC. This might lead to higher variance in the estimate, but speeds it up by multiple factors.
=> Change default parameters of ICC for speedup

dowhy/gcm/anomaly.py, dowhy/gcm/shapley.py
This should significantly speed up some calculations for larger graphs. In this regard, also increased the default samples for the anomaly attribution to balance the reduced number of Shapley run.
Tested on the notebooks and got equal results as before.
=> Change default parameters for Shapley estimator

dowhy/causal_refuters/overrule/BCS/load_process_data_BCS.py, dowhy/utils/encoding.py
The "sparse" parameter is deprecated and was renamed to "sparse_output".
=> Change OneHotEncoder parameter from "sparse" to "sparse_output"

docs/generate_docs.sh
This PR is an attempt to debug GH action failures wrt docsite publication. This lists out the content of the docsite to be pushed prior to synchronizing it.
=> list out docsite contents pre-publish

dowhy/utils/graph_operations.py
This PR fixes the issue of incorrect edges in `adjacency_matrix_to_graph` when the adjacency matrix is of type `np.matrix` by converting the matrix into a numpy array.
Related issue: https://github.com/py-why/dowhy/issues/887
=> Fix incorrect edges in `adjacency_matrix_to_graph`

dowhy/gcm/model_evaluation.py
pass the variable 'categorical' instead of the method 'is_categorical'
Based on the context of the codes, the variable 'categorical' should be passed in the function call of '_estimate_conditional_expectations' instead of the method 'is_categorical'
=> Fix issue #1254: pass the variable 'categorical'

.gitignore, dowhy/causal_graph.py, dowhy/graph.py, poetry.lock, tests/causal_identifiers/test_auto_identifier.py, tests/causal_identifiers/test_efficient_backdoor_identifier.py, tests/test_causal_graph.py
This PR extends the has_directed_path method to accept multiple treatment and outcome nodes. The approach taken here is as recommended from Issue #654:
> (2) more aggressively: every one of the treatments has at least one direct path to one of the outcomes. And, every one of the outcomes has a direct path from at least one of the treatments.
I opted to implement this by computing the list of all nodes reachable from our treatments, plus the list of all nodes that can reach our outcomes, rather than iteratively using networkx's [has_path method](https://networkx.org/documentation/stable/_modules/networkx/algorithms/shortest_paths/generic.html#has_path), since under the hood has_path is computing shortest paths, but we really do not need to incur the additional runtime of computing these …
=> Add support for non-singleton treatment/outcome sets to "has_directed_path" method

dowhy/gcm/causal_mechanisms.py
Hello,
I believe the noise terms for the DiscreteAdditiveNoiseModel are being computed with the wrong sign. The noise terms are added to the predicted value, therefore they should be computed by subtracting the predicted value from the true value. Currently, they are computed the other way, which would lead the noise distribution to be incorrect. They are computed correctly in the PostlinearNoiseModel implementation; I've updated the DiscreteAdditiveNoiseModel to function the same.
=> Fix incorrect signed noise terms for DiscreteAdditiveNoiseModel

docs/source/index.rst
Changing from
"Getting Starte" - "User Guide" - "Examples" - "dowhy package" - "Contributing" - "Release notes" - "Citing this package" to
"Getting Starte" - "User Guide" - "Examples" - "Citing this package" - "Contributing" - "Dowhy package" "Release notes"
Here, the last two entries are now 'hidden' under a "more" tab, i.e., putting the more important information to the front. Source references might be easier to find via the search function.
=> Change order of navigation entries in documentation

dowhy/gcm/falsify.py
Related to https://github.com/py-why/dowhy/issues/1268
=> Change np.math for math for compatibility

README.rst
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [DoWhy Guru](https://gurubase.io/g/dowhy) to Gurubase. DoWhy Guru uses the data from this repo and data from the [docs](https://www.pywhy.org/dowhy/v0.11.1/) to answer questions by leveraging the LLM.
In this PR, I showcased the "DoWhy Guru" badge, which highlights that DoWhy now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you …
=> Introducing DoWhy Guru on Gurubase.io

.github/workflows/docs-release.yml
v0.12 release: the docs-release had an error. See https://github.com/py-why/dowhy/actions/runs/11994244419
=> Fix typo error in docs-release workflow

dowhy/gcm/model_evaluation.py, tests/gcm/test_model_evaluation.py
The newest scikit-learn version removed the 'squared' parameter from mean_squared_error. This is now always True.
Addresses: https://github.com/py-why/dowhy/issues/1236
=> Fix issue with 'squared' parameter in model evaluation

dowhy/gcm/auto.py, dowhy/gcm/fitting_sampling.py, dowhy/gcm/util/general.py, tests/gcm/test_auto.py
The current implementation has the following limits:
- Only missing data in numerical features are supported
- Auto assignment only considers non-linear models for missing data
- Auto assignment only considers 3 different model types
- Not all GCM methods are supported. For example, distribution change based on missing data does not work due to the independence tests.
- Not tested thoroughly
To use the data with missing values, experimental_allow_nans has to be set to True in the assign_causal_mechanisms method. Manual model assignment should work as well.
Addresses: https://github.com/py-why/dowhy/issues/1300
=> Add experimental missing data support for GCM

dowhy/causal_estimator.py, dowhy/causal_estimators/econml.py, dowhy/causal_identifier/auto_identifier.py, dowhy/causal_model.py, dowhy/causal_refuters/graph_refuter.py
The `warn` method of logger is deprecated and warns user to use the `warning` method instead.
Sorry, do you have pre-commit for the formatting style?
=> Replace warn with warning

dowhy/gcm/auto.py
This PR modernizes NumPy array stacking by replacing deprecated aliases. It solves the following warnings which you can find in the [CI logs](https://github.com/py-why/dowhy/actions/runs/16490824292/job/46624862289#step:11:184): 
```python
DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
```
=> Correct vertical stacking in linearity check

dowhy/causal_prediction/algorithms/regularization.py
This pull request resolves issue #1306 by fixing two distinct CUDA-related errors that occur within the `conditional_reg` method in `dowhy/causal_prediction/algorithms/regularizer.py`.
The original implementation of the group index calculation runs correctly on CPU-only but fails on CUDA-enabled environments due to two main reasons:
1.  **Device Mismatch with NumPy:** The code attempted to use `np.concatenate` on `cumprod[:-1]`, which is a CUDA tensor when running on a GPU. This raises a `TypeError` as NumPy functions cannot operate directly on GPU tensors.
2.  **Unsupported Matrix Multiplication Type:** The matrix multiplication (`@` operator) for calculating `group_indices` involved two `LongTensor`s. This triggers a `RuntimeError: "addmv_impl_cuda" not implemented for 'Long'` because …
=> Fix CUDA errors in conditional regularizer
