py-why/dowhy

README.rst
requirements.txt
setup.py

It's a good thing to use requirements.txt file for holding project requirements, [you know](https://docs.microsoft.com/en-us/visualstudio/python/managing-required-packages-with-requirements-txt?view=vs-2017)?

Add and use requirements.txt

---

README.rst

Fixed some spelling mistakes for #Hacktoberfest

Fixed spelling mistakes

---

requirements.txt

Signed-off-by: cfreksen <casper@freksen.dk>
This fixes #20

Add pydot to requirements.txt

---

README.rst

Some grammatical enhancements to README.
Contributed as a part of Hacktoberfest 2018

Some grammatical enhancements to README

---

dowhy/causal_estimators/propensity_score_matching_estimator.py
dowhy/causal_estimators/propensity_score_stratification_estimator.py
dowhy/causal_estimators/propensity_score_weighting_estimator.py

* Removes camel-case variable names in favor of underscore-spaced names
* replaces hardcoded parameters with kwargs (previously hardcoded params are defaults)

consistent variable naming convention; replace hardcoded params

---

binder/apt.txt
binder/environment.yml

I just added the configuration files in order to run Binder. I tested the examples in my forked repo and they worked (except for the example I reported in issue #38 ), you can test the examples using the following path [https://mybinder.org/v2/gh/RaulPL/dowhy.git/binder_set_up](https://mybinder.org/v2/gh/RaulPL/dowhy.git/binder_set_up).
The rest is to add the path to the repository in  [mybinder](https://mybinder.org/) copy the badge and paste it on the README.md. It will look something like this:

Binder set up

---

dowhy/api/__init__.py
dowhy/api/causal_data_frame.py
dowhy/do_samplers/weighting_sampler.py
dowhy/utils/propensity_score.py

adds a propensity score weighing do sampler

added weighting sampler and prop score helper

---

dowhy/api/causal_data_frame.py
dowhy/causal_estimators/instrumental_variable_estimator.py
dowhy/causal_estimators/linear_regression_estimator.py
dowhy/causal_estimators/propensity_score_matching_estimator.py
dowhy/causal_estimators/propensity_score_stratification_estimator.py
dowhy/causal_estimators/propensity_score_weighting_estimator.py
dowhy/causal_graph.py
dowhy/causal_identifier.py
dowhy/do_samplers/multivariate_weighting_sampler.py
dowhy/utils/api.py
dowhy/utils/propensity_score.py

Adds propensity scoring module; 
Adds multivariate weighting estimator for do operation.

Multivariate state support

---

dowhy/api/causal_data_frame.py
dowhy/causal_graph.py
dowhy/do_sampler.py

fixes a bug due to the multivariate causal state and outcome support in the DoSampler, but univariate support in the CausalModel object. I'll make a PR in the next week or so to generalize the stack to make them compatible (preserving reverse compatibility), so the DoSampler can do MIMO causal inference!

Outcome do bug

---

dowhy/causal_refuters/placebo_treatment_refuter.py
dowhy/plotter.py

Modified strftime formatting to work on Windows & Linux rather than just Linux-based systems.
Modified overwriting of treatment_variable in placebo_treatment_refuter.py, due to list concatenation in construct_symbolic_estimator.py line 46 failing with str + list TypeError.

Minor bug fixes

---

README.rst
dowhy/api/causal_data_frame.py
tests/do_sampler/test_pandas_do_api.py

Automatically infer data by taking the default types defined within the pandas DataFrame

automatically infer data

---

dowhy/causal_refuters/add_unobserved_common_cause.py
tests/causal_refuters/base.py
tests/causal_refuters/test_add_unobserved_common_cause.py

Standardize output of refutation class. All the outputs now output a refutation object. All the new_effects are present as ndarrays.

Standardize output of refutation class.

---

dowhy/utils/propensity_score.py
tests/do_sampler/test_pandas_do_api.py

Add a test case to create dummy data to reproduce the minimum example. Changed the data type of treatment so as to make sure that an array is passed in place of string.

create dummy data and fix error in data type of treatment

---

dowhy/causal_refuters/bootstrap_refuter.py

This refuter provides the ability to find the robustness of the treatment effect by bootstrapping the data sample.

Add bootstrap refuter

---

dowhy/causal_estimators/econml_cate_estimator.py
tests/causal_estimators/test_econml_cate_estimator.py

* Made inputs to EconML estimators flexible which enables compatibility with future estimators
* Added smoke tests for EconML estimators

Changed argument logic for EconML estimators.

---

dowhy/causal_estimators/__init__.py
dowhy/causal_estimators/econml.py
dowhy/causal_model.py
tests/causal_estimators/test_econml_estimator.py

Create an API than can run third-party estimators

Move to new api

---

dowhy/causal_estimator.py
dowhy/causal_refuter.py
dowhy/causal_refuters/add_unobserved_common_cause.py
dowhy/causal_refuters/bootstrap_refuter.py
dowhy/causal_refuters/data_subset_refuter.py
dowhy/causal_refuters/dummy_outcome_refuter.py
dowhy/causal_refuters/placebo_treatment_refuter.py
dowhy/causal_refuters/random_common_cause.py

The aim of this PR is to add a default Confidence Interval function for all estimators. This is done by Bootstrapped Confidence Intervals.

Define confidence intervals

---

dowhy/causal_refuter.py
dowhy/causal_refuters/bootstrap_refuter.py
tests/causal_refuters/test_bootstrap_refuter.py

Add a common method in the Refuter base class, so as to allow the user to select the columns to be manipulated for different refuters.

move column selection to the base class

---

dowhy/causal_graph.py

Fix the missing arrows in the directed graph
Project: https://github.com/microsoft/dowhy/projects/4#card-29982754

fix networkx graph issues

---

dowhy/causal_refuters/bootstrap_refuter.py
dowhy/causal_refuters/data_subset_refuter.py
dowhy/causal_refuters/dummy_outcome_refuter.py
dowhy/causal_refuters/placebo_treatment_refuter.py
tests/causal_refuters/base.py
tests/causal_refuters/test_dummy_outcome_refuter.py

This allows us to have a well defined effect of the treatment on the outcome.
1. We find f(W) for a fixed value of t
2. For all the other values of t. We obtain the value of dummy outcome as:
y_dummy = h(t) + f(W)
If we originally started out with 
W
/    \
t --->y
y_dummy = f(W)
W
/    \
t --|->y
This ensures that we try to capture as much of W--->Y as possible
On adding h(t)
W
/    \
t --->y
h(t)

add true value to dummy outcome

---

dowhy/causal_estimators/generalized_linear_model_estimator.py
dowhy/causal_estimators/linear_regression_estimator.py
dowhy/causal_estimators/regression_estimator.py
dowhy/causal_refuters/add_unobserved_common_cause.py
dowhy/datasets.py
tests/causal_estimators/test_generalized_linear_model_estimator.py

Adding logistic regression and other GLM estimators

---

dowhy/causal_estimator.py
dowhy/causal_estimators/causalml.py
dowhy/causal_estimators/econml.py
dowhy/causal_estimators/instrumental_variable_estimator.py
dowhy/causal_estimators/propensity_score_matching_estimator.py
dowhy/causal_estimators/propensity_score_stratification_estimator.py
dowhy/causal_estimators/propensity_score_weighting_estimator.py
dowhy/causal_estimators/regression_estimator.py
dowhy/causal_estimators/two_stage_regression_estimator.py
dowhy/causal_model.py
dowhy/causal_refuters/dummy_outcome_refuter.py
dowhy/causal_refuters/placebo_treatment_refuter.py

2 new parameters to the CausalEstimate class so that it always stores the treatment and control values (and does not assume 0 or 1 as default)

Control and treatment value support for all refuters

---

.github/workflows/python-package.yml
dowhy/causal_refuters/add_unobserved_common_cause.py
dowhy/interpreters/confounder_distribution_interpreter.py
dowhy/interpreters/propensity_balance_interpreter.py
requirements-plotting.txt
requirements.txt
setup.py

Signed-off-by: Amit Sharma <amit_sharma@live.com>

Move matplotlib to an optional dependency

---

docs/source/example_notebooks/tutorial-causalinference-machinelearning-using-dowhy-econml.ipynb

- fixed a typo in the `instruments` variable
- added the items inside parentheses to help connect explanations to the code for more clarity

fixed a typo in variable name and added clarity

---

dowhy/causal_estimators/linear_regression_estimator.py

Analytic expression for confidence intervals breaks in the presence of effect modifiers (interactions in linear model).
This PR defaults to the bootstrap estimator when there are effect modifiers in linear regression, as mentioned in http://www.stat.columbia.edu/~gelman/arm/chap9.pdf

Bug in linear regression with effect modifiers: Switched to bootstrap confidence intervals 

---

dowhy/causal_refuters/add_unobserved_common_cause.py
dowhy/datasets.py

* Better interpretation for add_unobserved_common_cause
* Defaults for the confounders effect

Improving the sensitivity analysis 

---

README.rst

Added an news update for the workshop

Update README.rst with News tab

---

README.rst

* remove old links
* remove author byline

Updated readme to be consistent with Py-Why move

---

README.rst

* Add GCM-based inference features support

Update README News section

---

README.rst
docs/source/conf.py

* removes CLA from readme and mentions the pywhy code of conduct
*  changes the copyright text in docs

Update CLA in readme and copyright in docs

---

docs/source/gcm/user_guide/answering_causal_questions/attribute_distributional_changes.rst
docs/source/gcm/user_guide/introduction.rst

Signed-off-by: Ryan Russell <git@ryanrussell.org>

Improve Docs Readability

---

dowhy/gcm/auto.py
dowhy/gcm/ml/classification.py
dowhy/gcm/ml/regression.py
tests/gcm/test_auto.py

This module allows automatic assignment of causal mechanisms to nodes in the causal models.

Introduce gcm auto module

---

docs/source/gcm/user_guide/introduction.rst

Depends on https://github.com/py-why/dowhy/pull/462

Add auto assignment to introduction user guide for GCM

---

dowhy/gcm/_noise.py
dowhy/gcm/stats.py
dowhy/gcm/uncertainty.py
tests/gcm/test_stats.py
tests/gcm/test_uncertainty.py

This PR contains some stats and uncertainty related functions that are used by the following features:
- https://github.com/py-why/dowhy/pull/453

Introduce gcm uncertainty module

---

docs/source/example_notebooks/gcm_basic_example.ipynb

Making it consistent with the user guide.

Revise gcm basic example notebook

---

docs/source/gcm/user_guide/estimating_confidence_intervals.rst
docs/source/gcm/user_guide/index.rst

Depending on https://github.com/py-why/dowhy/pull/453

Add guide for using confidence intervals for gcms

---

dowhy/gcm/anomaly.py
dowhy/gcm/feature.py
dowhy/gcm/influence.py
dowhy/gcm/stats.py
tests/gcm/test_feature.py
tests/gcm/test_intrinsic_influence.py
tests/gcm/test_stats.py

- Rename samples_of_interest to baseline_samples
- Rename background_samples to randomization_samples

Rename parameters and revise docstrings

---

dowhy/gcm/__init__.py
dowhy/gcm/independence_test/__init__.py

Add simplified API for independence testing in GCM module

---

docs/source/gcm/user_guide/independence_tests.rst
docs/source/gcm/user_guide/index.rst
dowhy/gcm/independence_test/__init__.py

Depending on https://github.com/py-why/dowhy/pull/460

Add GCM independence test user guide

---

dowhy/gcm/cms.py

That's just a minor issue in the documentation where the links don't work.

Fix some links in docstrings

---

tests/gcm/test_arrow_strength.py

Removing unit tests that uses variance as attribution function. Here, this includes the unit test that compares the squared difference of the mean, which is equivalent to the variance in the corresponding test case. The variance attribution function is the default behavior of arrow_strength and already tested separately.

Refactor gcm arrow strength unit tests

---

dowhy/gcm/_noise.py
dowhy/gcm/fitting_sampling.py
dowhy/gcm/graph.py
dowhy/gcm/util/general.py
dowhy/gcm/whatif.py

Using pandas dataframes directly when generating samples, computing noise from observed data or when computing data from noise.

Simplify gcm sampling implementations

---

.github/workflows/python-package.yml
dowhy/gcm/util/__init__.py
dowhy/gcm/util/plotting.py
dowhy/gcm/util/pygraphviz.py
requirements-test.txt
tests/gcm/util/test_plotting.py
tests/gcm/util/test_pygraphviz.py

These are pure convenience functions and are not related to causal inference features.

Introduce gcm graph plotting utilities

---

docs/source/example_notebooks/nb_index.rst

Signed-off-by: Peter Goetz <pego@amazon.com>

Explain how to run example notebooks locally

---

docs/source/example_notebooks/gcm_401k_analysis.ipynb
docs/source/example_notebooks/rca_microservice_architecture.ipynb
dowhy/gcm/util/plotting.py
dowhy/gcm/util/pygraphviz.py

Follow up from: https://github.com/py-why/dowhy/pull/508#discussion_r913507745

Add optional parameter to gcm plot to change the figure size

---

docs/source/conf.py

For got to change that in
- https://github.com/py-why/dowhy/pull/561
before merging it.

Change from master to main in sphinx multiversion conf

---

.github/workflows/python-package.yml

The current trigger fired on 'master', which has been deprecated.

CI: Update GH Action Trigger

---

dowhy/causal_estimator.py
dowhy/causal_estimators/causalml.py
dowhy/causal_estimators/instrumental_variable_estimator.py
dowhy/causal_estimators/linear_regression_estimator.py
dowhy/causal_estimators/regression_discontinuity_estimator.py
dowhy/causal_model.py
dowhy/causal_refuters/graph_refuter.py
dowhy/interpreters/textual_interpreter.py

Fixes one part of #598 
Signed-off-by: Michael Marien <marien.mich@gmail.com>

Replace remaining print statements by appropriate levels of logging

---

docs/source/conf-rtd.py
docs/source/conf.py
poetry.lock
pyproject.toml

This change adds a little copy icon to all code snippets in the documentation.

Add sphinx_copybutton to documentation generation

---

tests/gcm/test_divergence.py

Refactor gcm divergence unit tests

---

tests/gcm/test_distribution_change.py

Refactor distribution change unit tests

---

tests/gcm/test_auto.py
tests/gcm/test_density_estimators.py

Smaller refactors in tests for auto and density estimator modules

---

tests/gcm/test_anomaly.py

Fix flaky gcm test for anomaly scoring with multivariate inputs

---

tests/gcm/test_fcms.py

Revise gcm FCM unit tests

---

tests/gcm/test_fcms.py

Fix a gcm unit test that was failing

---

.github/workflows/advanced-on-demand.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/nightly-tests.yml
.github/workflows/python-publish.yml
.gitignore
poetry.lock
pyproject.toml

- Update to Poetry 1.2
- Use `poetry publish` instead of `twine`

Use Poetry 1.2

---

tests/gcm/test_fcms.py
tests/gcm/test_intrinsic_influence.py

Make a gcm ICC and FCM unit test less flaky

---

docs/source/example_notebooks/community/README.md

Along with instructions for contributing notebooks to the folder.

Adding a new folder for community-sourced notebooks

---

pyproject.toml

This was now updated to latest Google Analytics JS code and should work again.

Use googleanalytics sphinx plugin from upstream

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-or-enhancement-request.md
.github/ISSUE_TEMPLATE/question.md

I propose to add these issue templates to ensure we get more context information when bugs are reported or questions get asked.

Add issue templates

---

tests/gcm/independence_test/test_kernel.py

Make conditional independence test based on regression less flaky

---

.github/workflows/build-docker-image-docs.yml
.github/workflows/docs.yml
docs/Dockerfile

- Introduce a GH Action to build Docker image for docs generation every time the Dockerfile is changed
- Trigger docs generation when a new Docker image was built
Addresses:
- https://github.com/py-why/dowhy/issues/690
- https://github.com/py-why/dowhy/issues/691

Change mechanics of Docker image build and usage

---

.github/workflows/docs.yml

This needs to point to the correct title.

Fix GH Actions workflow docs trigger

---

dowhy/gcm/distribution_change.py
tests/gcm/test_distribution_change.py

Add an option for auto assignment in distribution change attribution

---

tests/gcm/test_whatif.py

Make a gcm unit test for drawing from an interventional distribution less flaky

---

dowhy/causal_model.py

Signed-off-by: Andres Morales <andresmor@microsoft.com>

Fix avoid retrain estimator on causal_model API

---

dowhy/gcm/util/general.py
tests/gcm/util/test_general.py

Related to issue: https://github.com/py-why/dowhy/issues/722

Fix issue with identifying boolean values of dataframes in is_categorical

---

dowhy/causal_refuters/placebo_treatment_refuter.py

Fix for #719 
Signed-off-by: Andres Morales <andresmor@microsoft.com>

Check random_state type on placebo_treatment_refuter Fix #719

---

dowhy/gcm/ml/regression.py
tests/gcm/ml/test_regression.py

Fix issue with categorical inputs to gcm ProductRegressor

---

dowhy/gcm/distribution_change.py
dowhy/gcm/stochastic_models.py

Remove unnecessary double underscores in gcm module

---

dowhy/gcm/auto.py
dowhy/gcm/ml/__init__.py
dowhy/gcm/ml/classification.py
dowhy/gcm/ml/regression.py
tests/gcm/ml/test_classification.py
tests/gcm/ml/test_regression.py
tests/gcm/test_auto.py

This replaces the ProductRegressor.

Add polynom regressor and classifier to gcm

---

.github/workflows/docs-on-demand.yml

CI: Docs on Demand - Add missing step to get PR sha

---

dowhy/gcm/unit_change.py
tests/gcm/test_unit_change.py

The technical details are described in https://arxiv.org/abs/2206.12986
Signed-off-by: Kailash <111277+kailashbuki@users.noreply.github.com>

Add an API for unit change attribution

---

docs/source/example_notebooks/dowhy_lalonde_example.ipynb
docs/source/example_notebooks/dowhy_refutation_testing.ipynb
docs/source/example_notebooks/lalonde_pandas_api.ipynb
dowhy/datasets.py

... and use it in notebook examples.

Introduce dowhy.datasets.lalonde_dataset()

---

docs/source/example_notebooks/gcm_rca_microservice_architecture.ipynb
dowhy/gcm/util/__init__.py
dowhy/gcm/util/plotting.py

We're using function in so many places in notebooks, similar to the graph plot utility that I think it's worth providing this as a convenience function.

Add convenience function to plot attribution scores

---

dowhy/gcm/__init__.py
dowhy/gcm/independence_test/__init__.py
dowhy/gcm/independence_test/general_cov_measure.py
tests/gcm/independence_test/test_general_cov_measure.py

Add independence test based on the General Covariance Measure

---

dowhy/gcm/auto.py
dowhy/gcm/ml/__init__.py
dowhy/gcm/ml/autolguon.py
poetry.lock
pyproject.toml
tests/gcm/ml/test_autogluon.py
tests/gcm/test_auto.py

This extends the auto model assignment by the 'BEST' parameter, which returns an autogluon model (i.e., an auto ML model).

Adding autogluon as optional dependency to gcm module

---

dowhy/causal_estimators/econml.py
dowhy/utils/api.py
tests/causal_estimators/test_econml_estimator.py

Signed-off-by: Egor Kraev egor.kraev@wise.com

An attempt at a DCO-compliant version of multivalue treatment PR

---

.github/workflows/advanced-on-demand.yml
.github/workflows/ci.yml
.github/workflows/docs-ci.yml
.github/workflows/docs-release.yml
.github/workflows/docs.yml
.github/workflows/nightly-tests.yml
poetry.lock
pyproject.toml

Run 'poetry update'; remove econml, pygraphviz from devDeps - use extras

---

.github/workflows/advanced-on-demand.yml
.github/workflows/ci.yml
.github/workflows/docs-ci.yml
.github/workflows/docs-release.yml
.github/workflows/docs.yml
.github/workflows/nightly-tests.yml
dowhy/causal_estimators/causalml.py
poetry.lock
pyproject.toml

* Remove causalml dependency. Related to #783 
* Fix econml to be required (right now without econml it will fail to import dowhy)
* Update lock file

Remove causalml dep

---

.github/workflows/ci-install.yml

Fix install check in fork-based PRs

---

.github/workflows/ci-install.yml

Update ci-install trigger

---

docs/source/example_notebooks/dowhy_causal_discovery_example.ipynb

signficant -> significant
Signed-off-by: Ikko Ashimine <eltociear@gmail.com>

Fix typo in dowhy_causal_discovery_example.ipynb

---

dowhy/causal_refuter.py

Simplify and fix p-value calculation in bootstrap refutation test: Fixes bug in https://github.com/py-why/dowhy/issues/804

Bootstrap p value fix

---

dowhy/gcm/ml/regression.py
tests/gcm/ml/test_regression.py

This should reduce potential overfitting issues.

Set gcm polynomial regressor to 2 degree by default

---

tests/gcm/test_auto.py

Make unit test for auto assign linear model less flaky

---

tests/gcm/test_graph.py
tests/gcm/test_intrinsic_influence.py
tests/gcm/test_ml.py

Rename some gcm unit tests

---

tests/gcm/independence_test/test_regression.py

Rename regression based indep test unit tests

---

tests/gcm/test_shapley.py

Rename shapley unit tests

---

tests/gcm/test_stats.py

Rename gcm stats unit tests

---

dowhy/causal_estimators/econml.py
dowhy/utils/api.py

Signed-off-by: Andres Morales <andresmor@microsoft.com>

Fix issue #820 - Estimate Effect fails with Econml DML estimator

---

dowhy/gcm/util/plotting.py

Add parameter in bar_plot to sort names alphabetically

---

tests/gcm/test_stochastic_models.py
tests/gcm/test_uncertainty.py
tests/gcm/test_validation.py
tests/gcm/test_whatif.py

Rename remaining gcm unit tests

---

dowhy/causal_model.py
tests/test_causal_model.py

Closes #810. 
Introduces a `UserWarning` that is emitted if there are any graph variables that are not contained in the observed data (`self._data`). Adds a unit test for this implementation.
Currently, the return values of `self.get_common_causes()`, `self.get_instruments()` and `self.get_effect_modifiers()` are considered as graph variables. 
In issue thread #810 there is also a suggestion to point out potential misspellings, for which I'd be happy to amend additional logic. See the questions in the last bullet point below to clarify the implementation in case we wish to add this. 
Design considerations and questions to reviewers:
* Should we emit this via `self.logger.warning` instead? In my opinion, this will frequently point out improper usage (e.g., a typo in the columns of …

Enhancement: warn about unobserved graph variables in `causal_model.identify_effect`.

---

dowhy/gcm/confidence_intervals_cms.py

The new parameter allows to indicate whether existing causal mechanisms should be overridden by inferred ones based on the data. This would also include uncertainties of the model selection when computing confidence intervals.

Add a new paramter to fit_and_compute for confidence intervals

---

docs/source/user_guide/gcm_based_inference/answering_causal_questions/quantify_arrow_strength.rst

Revise arrow strength user guide

---

dowhy/gcm/influence.py
tests/gcm/test_arrow_strength.py

- Speed up by reducing tolerance threshold
- Increase default value for num_samples_conditional to improve accuracy
- Fix bug when num_samples_conditional is set to a higher number than the actual number of given samples
- Clarify tolerance parameter in docstring

Revise gcm arrow strength

---

dowhy/gcm/shapley.py

- In the "early stopping" method, the runs were converging slowly when a Shapley value is exactly zero, because the change was always considered as 100%. Now, if the Shapley value between two consecutive runs are exactly zero, then it is considered as 'converging'.
- Since the Shapley estimator supports the estimation of multiple vectors of Shapley values at the same time, this change also introduces some logic to keep track of the convergence for each vector individually.

Revise early stopping convergence critera for Shapley value estimator 

---

dowhy/gcm/shapley.py
tests/gcm/test_shapley.py

- Simplify the sampling process of permutations
- Using Halton sequence now instead of Sobol, since Halton generalizes beyond a basis of 2
This should also fix the current build error.

Revise gcm Shapley estimator

---

dowhy/gcm/shapley.py
tests/gcm/test_shapley.py

Before, the early stopping did not stop even if the threshold was reached.

Fix bug in Shapley estimator

---

pyproject.toml

This makes running tests locally much faster.

Offer a test option to run tests without notebooks

---

dowhy/causal_refuter.py

Bug fix: revert significance value of refutations to 0.05

---

tests/gcm/independence_test/test_kernel.py
tests/gcm/independence_test/test_regression.py
tests/gcm/test_intrinsic_influence.py

Another PR to address flaky builds.

Reduce flakiness in some unit tests

---

dowhy/datasets.py
tests/test_datasets.py

This replaces the original PR https://github.com/py-why/dowhy/pull/1003

Add sales profit dataset generator

---

dowhy/gcm/auto.py
dowhy/gcm/distribution_change.py
tests/gcm/test_distribution_change.py

Feature - Now users can enter the list of invariant nodes to the distribution_change function to remove them from analysis

Invariant nodes removal

---

dowhy/causal_estimators/regression_estimator.py

Original implementation of _do for RegressionEstimators calculated individual outcomes for all dataframe rows, and then returned the mean(). However, for many use-cases it is helpful to have the individual outcomes for further analysis. This commit moves the existing implementation (without changes) to a new function interventional_outcomes() which returns all outcomes. The implementation of _do() now only calls mean() on the returned values. The behaviour of _do() is unchanged.

Expose individual interventional outcomes from RegressionEstimator _do operator (#1011)

---

dowhy/gcm/auto.py
dowhy/gcm/causal_mechanisms.py
dowhy/gcm/independence_test/generalised_cov_measure.py
dowhy/gcm/influence.py
dowhy/gcm/ml/regression.py
dowhy/gcm/stochastic_models.py
tests/gcm/test_auto.py

The summary object contains information about the evaluated models and model choices. This object is printable to provide quick summary.

GCM auto assignment now returns a summary object

---

dowhy/gcm/divergence.py
dowhy/gcm/stochastic_models.py
tests/gcm/test_arrow_strength.py
tests/gcm/test_divergence.py
tests/gcm/test_fcms.py

This should work better with multivariate data and mixed data types. However, it is slower than the knn approach.

Add new method to estimate KL divergence using classifier

---

docs/source/user_guide/causal_tasks/estimating_causal_effects/index.rst
dowhy/causal_model.py

Link list of estimators in estimate_method docstring

---

.github/workflows/ci.yml
README.rst

Adding a twine check that runs automatically on all PRs. twine checks the conditions that PyPI checks on the built package distribution.

Fix errors in README and add a test to avoid such errors in the future

---

dowhy/causal_estimator.py

Fix double counting in two sided bootstrap confidence intervals

---

.github/workflows/docs-release.yml
.github/workflows/docs.yml

* Only deploy /main subfolder when main is updated
* Only deploy new version  + root assets when cutting a new release

Update docsite publish steps

---

dowhy/gcm/divergence.py

Related to: https://github.com/py-why/dowhy/issues/1213

Fix issue in KL divergence estimator with non-unique values

---

docs/source/user_guide/causal_tasks/estimating_causal_effects/identifying_causal_effect/backdoor.rst
docs/source/user_guide/causal_tasks/estimating_causal_effects/identifying_causal_effect/id_algorithm.rst

method_name is the correct parameter name

Fix Documentation Using The Incorrect Method
